### ISSUE TITLE
Nullpointer Exception at FastPack.java:164 & FastPack.java:248)

### ISSUE THREAD

**Issue by thisischrys** [MCUpdater/FastPack#3]
I'm making a modpack based on Resonant Rise 3, and it all works fine until I try adding some litemods to it. Not sure that's the issue, it could just be that I have too many mods. It's quite big.

Full output here: http://pastebin.com/HUgN0J4V
Here are all the files it is processing: http://pastebin.com/T09irVK7

https://github.com/MCUpdater/FastPack/blob/master/src/main/java/org/mcupdater/fastpack/FastPack.java#L164
and
https://github.com/MCUpdater/FastPack/blob/master/src/main/java/org/mcupdater/fastpack/FastPack.java#L248 (no idea what could be wrong here)

**Comment by smbarbour** [comment]
Those lines do not match up with the version of FastPack you are using.  How long ago did you download it?

**Comment by thisischrys** [comment]
A few weeks. I'll redownload and try again tonight.

**Comment by thisischrys** [comment]
works fine in the latest version
